### ISSUE TITLE
3-generaton trio analysis possible?

### ISSUE THREAD

**Issue by Solyris83** [HKU-BAL/Clair3-Trio#1]
Hi, I am toying with an idea to collect sample for a family with a condition of interest and there is 3 generation available, grandparent do not have conditon while 1 parent and 2 child has the condition. Can this kind of family structure be used effectively to identify variant?  Also I currently only identified 1 family so far, does it work with 1 family or more family is required?

**Comment by sujunhao** [comment]
Hi, Clair-Trio only support input with one family trio of two parents, and one child together.
If you have a 3-generation trio, you can try to split your data into a trio case for Clair3-Trio input.
