### ISSUE TITLE
About the creating tensors for model training part

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/Clair3-Trio#11]
Dear author：
In the creating tensors for model training part, i see 
each tensors are generated from combination of trio samples
e.g. in the following example, we generation different combination from [10x, 30x, 60x, 80x] data from HG002 trio into
combination of (Child, Parent1, Parent2): (10x, 10x, 10x), (30x, 10x, 10x)

I trained with this example and got similar results to the paper on 10X data sets, but did not work well on 20X and above data sets. I would like to ask you what method you used in your final training to generate tensor.
Thank you！

**Comment by sujunhao** [comment]
Hi, 

We are using the same scripts shared in our repo [here](https://github.com/HKU-BAL/Clair3-Trio/blob/trio/docs/trio/trio_training.md#train-a-model-for-clair3-trio-trio-calling-v4).

For better results with data higher than 10x, ensure you have training data above 10x.

Regards,
JH
