### ISSUE TITLE
Update of trio models

### ISSUE THREAD

**Issue by jimmykhchiu** [HKU-BAL/Clair3-Trio#12]
Hi,

I would like to know whether there is any plan to upload more trio models like Clair3 (rerio) in near future? Also, are the pre-trained trio models trained with Ashkenazim family samples (HG002-4) only?

Thank you.
Jimmy

**Comment by sujunhao** [comment]
Hi,

Currently, we don't have a plan to provide more new models. However, we are working on a new version of Clair3-Trio (scheduled for spring 2024) to improve its accuracy in certain cases including diverse coverage at trio and detection of de novo variants.

And yes, our models provided are only trained on the HG002 trio.

Regards,
JH

**Comment by jimmykhchiu** [comment]
Thanks @sujunhao for the update.
