### ISSUE TITLE
Question about variant calling conditions

### ISSUE THREAD

**Issue by SanVerb** [HKU-BAL/Clair3-Trio#14]
Hello, I was wondering how decisions are made for a position in the child to be phased or not. I read your paper, but found it quite difficult to understand as I'm quite new to the field of bioinformatics.

For example: I was wondering why the following 50 positions are not called in the child; which parameters are considered?

Total positions in a specific region in my multi vcf): 185
-> multivcf is merge of child, father, mother vcf's which were generated using clair3-trio
![image](https://github.com/HKU-BAL/Clair3-Trio/assets/119843490/ca73c18d-9d7f-4f5b-b67f-ffcf47b1388c)

**50 positions not called in the child:**
['chr15', '23633794', '.', 'T', 'TC', '13.67', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:13:17:12,5:0.2941', './.:.:.:.:.']
['chr15', '23635280', '.', 'G', 'GA', '3.23', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '1/1:3:18:9,3:0.1667', './.:.:.:.:.']
['chr15', '23635700', '.', 'C', 'CA', '3.88', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:3:16:3,4:0.25', './.:.:.:.:.']
['chr15', '23637449', '.', 'A', 'T', '15.58', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:15:23:20,3:0.1304']
['chr15', '23640201', '.', 'G', 'A', '22.48', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:22:26:19,7:0.2692']
['chr15', '23646664', '.', 'G', 'A', '24.05', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:18:10,6:0.3333']
['chr15', '23666327', '.', 'CT', 'C', '6.03', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:6:30:11,18:0.6', './.:.:.:.:.']
['chr15', '23667222', '.', 'A', 'AC', '6.32', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:6:16:12,2:0.125']
['chr15', '23667223', '.', 'A', 'C', '9.42', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:9:16:12,4:0.25']
['chr15', '23667225', '.', 'AAC', 'A', '1.66', 'LowQual', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:1:16:13,3:0.1875']
['chr15', '23675929', '.', 'G', 'GTA', '21.11', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:21:19:10,8:0.4211']
['chr15', '23675953', '.', 'C', 'CAT', '9.42', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:9:19:14,5:0.2632']
['chr15', '23675962', '.', 'G', 'A', '13.41', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:13:19:13,5:0.2632']
['chr15', '23676022', '.', 'A', 'G', '2.79', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:2:19:8,6:0.3158']
['chr15', '23676053', '.', 'A', 'G', '7.6', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:7:19:12,4:0.2105']
['chr15', '23676063', '.', 'A', 'ACACACATAT', '5.79', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:5:19:8,1:0.0526']
['chr15', '23676077', '.', 'C', 'T', '7.85', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:7:19:9,10:0.5263']
['chr15', '23676083', '.', 'A', 'T', '7.13', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:7:19:11,8:0.4211']
['chr15', '23676084', '.', 'A', 'T', '3.88', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:3:19:8,9:0.4737']
['chr15', '23676090', '.', 'C', 'CAT', '9.11', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:9:19:13,4:0.2105']
['chr15', '23676096', '.', 'T', 'C', '10.26', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:10:19:13,4:0.2105']
['chr15', '23676127', '.', 'T', 'C', '5.9', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:5:20:16,4:0.2']
['chr15', '23676134', '.', 'A', 'G', '7.08', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:7:20:12,4:0.2']
['chr15', '23676160', '.', 'C', 'T', '5.73', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:5:20:9,9:0.45']
['chr15', '23676163', '.', 'A', 'ATATG', '6.29', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:6:20:15,2:0.1']
['chr15', '23676171', '.', 'A', 'AT', '9.76', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:9:20:14,4:0.2']
['chr15', '23676195', '.', 'A', 'G', '7.24', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:7:20:14,3:0.15']
['chr15', '23676248', '.', 'T', 'C', '10.17', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:10:20:13,7:0.35']
['chr15', '23676270', '.', 'CAT', 'C', '11.49', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:11:20:11,9:0.45']
['chr15', '23676288', '.', 'A', 'G', '11.53', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:11:20:12,8:0.4']
['chr15', '23676359', '.', 'T', 'TATATGTG', '0', 'LowQual', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:0:20:10,6:0.3']
['chr15', '23679018', '.', 'C', 'G', '24.09', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:24:28:12,16:0.5714', './.:.:.:.:.']
['chr15', '23679021', '.', 'G', 'A', '24.28', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:21:13,8:0.381']
['chr15', '23679039', '.', 'T', 'G', '24.08', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:20:12,8:0.4']
['chr15', '23679139', '.', 'A', 'G', '24.46', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:20:12,8:0.4']
['chr15', '23679561', '.', 'A', 'G', '22.81', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:22:20:13,6:0.3']
['chr15', '23679909', '.', 'T', 'C', '24.1', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:19:11,8:0.4211']
['chr15', '23680153', '.', 'C', 'T', '24.16', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:18:11,7:0.3889']
['chr15', '23680262', '.', 'G', 'A', '7.56', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:5:29:23,5:0.1724', '0/1:7:19:16,3:0.1579']
['chr15', '23680525', '.', 'C', 'CA', '5.07', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', '0/1:5:29:22,4:0.1379', './.:.:.:.:.']
['chr15', '23680747', '.', 'A', 'G', '24.53', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:19:12,6:0.3158']
['chr15', '23681185', '.', 'T', 'C', '23.84', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:23:19:12,7:0.3684']
['chr15', '23681236', '.', 'G', 'T', '24.92', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:19:13,6:0.3158']
['chr15', '23681341', '.', 'G', 'GT', '6.85', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:6:19:13,6:0.3158']
['chr15', '23681491', '.', 'G', 'GAA', '4.81', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:4:20:10,2:0.1']
['chr15', '23681768', '.', 'A', 'AG', '12.36', 'LowQual', 'P', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:12:21:7,11:0.5238']
['chr15', '23682288', '.', 'G', 'T', '24.9', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:21:13,8:0.381']
['chr15', '23683947', '.', 'G', 'T', '25.63', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:25:22:13,8:0.3636']
['chr15', '23683960', '.', 'G', 'A', '23.99', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:23:22:12,9:0.4091']
['chr15', '23683973', '.', 'T', 'A', '24.3', 'PASS', 'T', 'GT:GQ:DP:AD:AF', './.:.:.:.:.', './.:.:.:.:.', '0/1:24:22:13,9:0.4091']

Kind regards

Sanché Verbeeck

**Comment by sujunhao** [comment]
To phase a child position, Clair3-Trio needs to first call nearby SNP as input for the [WhatsHap](https://whatshap.readthedocs.io/) phasing module for phasing. The number of SNP surrounding a specific position may determine whether the position will be phased or not.

To find out why some positions are not called via Clair3-Trio, checking the BAM files or using IGV to visualize the alignment may give you some hints. A position may not call for 1) no or insufficient read or alignment for a target position; 2) the position is hard to call for low mapping quality like some "LowQual" variants found via Clair3-Trio.

Regards,
Junhao

**Comment by SanVerb** [comment]
I see! Thank you! :)

**Comment by SanVerb** [comment]
Hello

I checked the BAM files, but the variants really are not called at those positions, despite adequate coverage and mapping quality (60). These positions are heterozygous in mother and child and are called as such in mother and child, but they are homozygous reference in the father. Instead of calling the variants as reference in the father at these positions (so as: 0/0), it does not call them at all (./.), nor does it provide any information on the read depth or other variant metrics (`./.:.:.:.:.`).

kind regards

Sanché Verbeeck

**Comment by SanVerb** [comment]
Hello

I checked the BAM files, but the variants really are not called at those positions, despite adequate coverage and mapping quality (60). 

Similarly, I made another strange observation. Many positions (mapping quality 60, and most of them marked as PASS) are heterozygous in mother and child and are called as such in mother and child, but they are homozygous reference in the father. Instead of calling the variants as reference in the father at these positions (so as: 0/0), it does not call them at all (./.), nor does it provide any information on the read depth or other variant metrics (`./.:.:.:.:.`).

kind regards

Sanché Verbeeck

**Comment by sujunhao** [comment]
Hi,

Thanks for your information, did you turn on "--print_ref_calls" to show reference calls in Clair3-Trio? Clair3-Trio did not output the reference call by default. In case you turned on the "print_ref_calls" [option](https://github.com/HKU-BAL/Clair3-Trio?tab=readme-ov-file#options) and still get the missing called results, could you please share your bam file (for alignment in the problematic regions) with me by send to my email address "jhsu@connect.hku.hk"? I will have a further investigation of the input files you provided.

Regards,
Junhao

**Comment by SanVerb** [comment]
Hello,

No I did not! I completely missed that option! I will come back to you later!

kind regards

Sanché Verbeeck

**Comment by SanVerb** [comment]
Hello again

Using the --print_ref_calls did indeed solve the problem. Thank you very much!

In my opinion, it would make more sense for the output to contain reference calls by default, as the generated output now is what I would actually expect from a trio variant calling.

Nevertheless, the tool is awesome as it significantly improved my pedigree phasing result on LRS data!

Good luck with future projects!

kind regards

Sanché Verbeeck

**Comment by sujunhao** [comment]
Hi,
It's nice to know that the problem is solved, and many thanks for your feedback.

Regards,
Junhao
