### ISSUE TITLE
chr1 data

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/Clair3-Trio#2]
Where can I download the training data chr1 you used in Figure 5?Thank you very much！

Figure 5. Comparison of different architectures and shapes for calling variants from trios. All results were trained on chr1 and tested on chr20.

**Comment by sujunhao** [comment]
Hi, the original data can be downloaded from this [page](https://github.com/HKU-BAL/Clair3-Trio/blob/trio/docs/trio/training_data.md). And the training data can be generated from this [page](https://github.com/HKU-BAL/Clair3-Trio/blob/trio/docs/trio/trio_training.md).

**Comment by shiying-sxu** [comment]
Thanks for your answer, I was asking if there is any chr1 data directly used for training

**Comment by sujunhao** [comment]
Thank you for your follow-up question. 

To clarify, we do not directly share the parsed chr1 data for training purposes. However, we do provide a shared training script that can generate the chr1 data from the original bam file. This approach ensures that the data is consistent across all users and allows for greater flexibility in the training process. If you have any further questions or need assistance with the script, please let us know.

**Comment by shiying-sxu** [comment]
I would like to follow the Comparison of different architectures and shapes for calling variants from trios ,All results were trained on chr1 and tested on chr20 as your paper(fig 5). Therefore, i want to obtain the corresponding data set of chr1 below
can you share the training script that can generate the chr1 data from the original bam file?&nbsp;


&nbsp;Thank you !
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Mar 21, 2023 03:52 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [HKU-BAL/Clair3-Trio] chr1 data (Issue #2)

&nbsp;



 
Thank you for your follow-up question.
 
To clarify, we do not directly share the parsed chr1 data for training purposes. However, we do provide a shared training script that can generate the chr1 data from the original bam file. This approach ensures that the data is consistent across all users and allows for greater flexibility in the training process. If you have any further questions or need assistance with the script, please let us know.

**Comment by sujunhao** [comment]
Hi, the original data can be downloaded from this [page](https://github.com/HKU-BAL/Clair3-Trio/blob/trio/docs/trio/training_data.md). And the script for generating the data is available on this [page](https://github.com/HKU-BAL/Clair3-Trio/blob/trio/docs/trio/trio_training.md). Please follow the training script to generate the training data.
