### ISSUE TITLE
gVCF output option not working

### ISSUE THREAD

**Issue by biorococo** [HKU-BAL/Clair3-Trio#3]
Clair-trio won't output gVCF format when enabling "--gvcf" 

There is no printed error other than:

cat: 'test/tmp/gvcf_tmp_output/*.tmp.g.vcf': No such file or directory
FileNotFoundError: [Errno 2] No such file or directory: 'SortVcf'

Let me know if there is any other info you need. Thanks.

**Comment by sujunhao** [comment]
Thanks for your message.

Currently, Clair3-Trio doesn't provide the function to output the gVCF file. The "--gvcf" option on the help page is a legacy option and is not currently functional.  Sorry for any confusion regarding the gVCF output option in Clair3-Trio.

And we updated the repo and docker image version without the "--gvcf" option on the help page.

**Comment by aquaskyline** [comment]
@biorococo it takes some engineering efforts to add support for GVCF in Clair3-Trio, but it's doable. Could you share with us how would you like to use Clair3-Trio so we can better plan for the upgrade.

**Comment by aquaskyline** [comment]
GVCF output added to v0.5

**Comment by biorococo** [comment]
Thanks a lot for reopening the issue and add this output so quickly! will be helpful for downstream analysis. I will give this new version a try.

**Comment by biorococo** [comment]
Hi again, I got my gVCF using the new version! although I'm getting the following error when using bcftools on the gvcf produced:

[W::vcf_parse_info] INFO 'T' is not defined in the header, assuming Type=String

For reference see INFO fields in header:
##INFO=<ID=P,Number=0,Type=Flag,Description="Result from pileup calling">
##INFO=<ID=F,Number=0,Type=Flag,Description="Result from full-alignment calling">

Also see some example records:
chr1	10108	.	C	CT,<NON_REF>	14.40	PASS	T	GT:GQ:DP:AF	0/1:14,0:27:0.5556,990,990,990
chr1	10199	.	A	C,<NON_REF>	8.24	PASS	T	GT:GQ:DP:AF	0/1:8,0:27:0.2593,990,990,990

**Comment by sujunhao** [comment]
Hi,

Thanks for your information, the error is caused by a missing header line in the gvcf output.

Adding a line in the gvcf output like:

`##INFO=<ID=T,Number=0,Type=Flag,Description="Result from trio calling">`

will fix this error.

 I will fix it in one week and let you know when the mistake is fixed.

**Comment by sujunhao** [comment]
Hi, the gVCF header problem is fixed at v0.6. thanks.
