### ISSUE TITLE
--enable_phasing does not produce expected output

### ISSUE THREAD

**Issue by biorococo** [HKU-BAL/Clair3-Trio#4]
When using --enable_phasing I can't see any phased SNV on my final VCF. This happens in v0.4 and v0.5.

**Comment by sujunhao** [comment]
Hi, thanks for your information, the "--enable_phasing" option is not exposed in the v0.5 version now. We will add the "--enable_phasing" option in the next update.

**Comment by sujunhao** [comment]
Hi @biorococo, the "--enable_phasing" support is added in v0.6, thanks.
