### ISSUE TITLE
Illumina models

### ISSUE THREAD

**Issue by gambalab** [HKU-BAL/Clair3-Trio#5]
Hi,
Really thank you for the tool. Are there any plans to add also a clair3-Trio-illumina for Illumina short reads and a pre-trained model to use clair3-Trio with Illumina long reads?

**Comment by sujunhao** [comment]
Hi,

Thank you for your kind words and interest in our tool. Currently, our tool only supports ONT data, and we don't have plans to add support for Illumina short reads at this time.

However, we appreciate your feedback for future development. We will definitely consider extending our tool to support Illumina data in the future, but we don't have a timeline for it yet.

Thank you again for your support, and please let us know if you have any other questions or feedback.

JH

**Comment by gambalab** [comment]
Hi, thank you for the quick answer. However, I was wondering if you could give me me some indication of how I could achieve that. 

I was thinking of trying to train a clair3-trio model using the HG002-04 sequenced with Illumina from your page [HERE](https://github.com/HKU-BAL/Clair3/blob/main/docs/training_data.md). While using for clair3, the already trained by you Illumina model.  This should allow me to use clair3-trio on Illumina data. Is this correct?

**Comment by aquaskyline** [comment]
It'd be tricky because Clair3-Trio didn't implement some essential mechanisms to ensure a good calling quality for Illumina data, such as realignment. For Illumina trio calling, GATK is our go-to solution in mind.
