### ISSUE TITLE
Q20+ data（FASTQs and BAMs） need

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/Clair3-Trio#7]
Hello! I want to obtain Q20+ data (FASTQs and BAMs format) for experimental purposes. However, I found on the main page that almost all of them need AWS to download, is there any other way or website? Since I am a student without a VISA card, I cannot register an AWS account.
Hope to get your help

**Comment by sujunhao** [comment]
Hi, 

you can download the Q20+ data with the `aws` command line [interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html), e.g. 
`aws s3 sync --no-sign-request s3://ont-open-data/giab_lsk114_2022.12/analysis/wf-human-var-output/hg004_sup_v4/ .`

The data link for Q20+ is available on this [page](https://labs.epi2me.io/askenazi-kit14-2022-12/).
