### ISSUE TITLE
Exceeding walltime and no output

### ISSUE THREAD

**Issue by ilenia6** [HKU-BAL/Clair3-Trio#9]
Hi, 
I am trying to run a Clair3-Trio analysis on a trio using the script run_clair3_trio.sh with the following options:
un_clair3_trio.sh \
  --bam_fn_c=child.bam \
  --bam_fn_p1=parent1.bam \
  --bam_fn_p2=parent2.bam \
  --output=output_dir/ \
  --ref_fn=ref.fasta \
  --threads=12 \
  --model_path_clair3=/path/to/Clair3-Trio/models/clair3_models/r941_prom_hac_g360+g422 \
  --model_path_clair3_trio=/path/to/Clair3-Trio/models/clair3_trio_models/c3t_hg002_g422 \
  --whatshap=/path/to/clair3_env/bin/whatshap \
  --include_all_ctgs \
  --enable_output_phasing \
  --enable_output_haplotagging
  
where the *bam files have been produced aligning the raw reads against my ref genome using minimap2.
However, it seems that the runtime exceeds 50 hours (which is my walltime limit). In addition, no output file have been produced.
  
Is there anyone who had the same problems? Is there any option I have to change in order to speed up the analysis or something I am actually missing?
  
Thank you for your help!

**Comment by aquaskyline** [comment]
Can you show us the log file.
